#!/bin/bash

# . $LIBCONFIG/includes/support.sh

# Regen
/var/lib/pulse2/clients/generate-agents && /var/lib/pulse2/clients/create-repos.sh

#test -f /etc/mmc/pulse2/package-server/package-server.ini.local && \
#  pulse_ip=`grep -E '^public_ip[[:space:]]*=' /etc/mmc/pulse2/package-server/package-server.ini.local | cut -d= -f2 | sed 's!\s!!g' | grep -E '^([0-9]{1,3}\.){3}[0-9]{1,3}$'`
#if [ -z ${pulse_ip} ]; then
#  test -f /etc/mmc/pulse2/package-server/package-server.ini && \
#  pulse_ip=`grep -E '^public_ip[[:space:]]*=' /etc/mmc/pulse2/package-server/package-server.ini | cut -d= -f2 | sed 's!\s!!g' | grep -E '^([0-9]{1,3}\.){3}[0-9]{1,3}$'`
#fi
## Still empty ?!?!?
#if [ -z ${pulse_ip} ]; then
#  echo "Unable to determinate IP address using public_ip field from"
#  echo "package-server.ini. Fix your configuration."
#  echo
#  exit 1
#fi
#
#mkdir -p /var/lib/pulse2/clients/agent/win32/
#bin_file="/var/lib/pulse2/clients/agent/win32/win32.tar.gz"
#if [ -e "${bin_file}" ]; then
#  echo
#  echo "${bin_file} already available. Skipping download."
#  echo
#else
#  echo
#  echo "Downloading ${bin_file}..."
#  curl --progress-bar -o /var/lib/pulse2/clients/agent/win32/win32.tar.gz http://pulse.mandriva.org/pub/pulse2/client/windows/win32/pulse2-smart-agent/win32.tar.gz
#  echo
#  if [ ! -e ${bin_file} ]; then
#    echo
#    echo "${bin_file} download failed. Please restart."
#    echo
#    exit 1
#  fi
#fi
#
#tar xzf /var/lib/pulse2/clients/agent/win32/win32.tar.gz --directory /var/lib/pulse2/clients/agent/win32/
#rm /var/lib/pulse2/clients/agent/win32/win32.tar.gz
#
#sed -i "s/@@PULSE_INTERNAL_IP@@/${pulse_ip}/" /var/lib/pulse2/clients/agent/win32/installer.nsi
#sed -i "s/@@PULSE_PUBLIC_FQDN@@/${SAFQDN}/" /var/lib/pulse2/clients/agent/win32/installer.nsi
#
#makensis /var/lib/pulse2/clients/agent/win32/installer.nsi
#
