Document: univention-pulse
Title: Debian univention-pulse Manual
Author: <insert document author here>
Abstract: This manual describes what univention-pulse is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/univention-pulse/univention-pulse.sgml.gz

Format: postscript
Files: /usr/share/doc/univention-pulse/univention-pulse.ps.gz

Format: text
Files: /usr/share/doc/univention-pulse/univention-pulse.text.gz

Format: HTML
Index: /usr/share/doc/univention-pulse/html/index.html
Files: /usr/share/doc/univention-pulse/html/*.html
